# Xenia Mailer - FidoNet Technology Mailer
# Copyright (C) 1987-2001 Arjen G. Lentz
#
# This file is part of Xenia Mailer.
# Xenia Mailer is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

.RESPONSE_LINK: tlink link

# Compiler flags: C=Compiler, T=Assembler, L=Linker
# MODEL=Memory Model (large!)
# /* Warning: option -1 == 80286 instructions!!  */
# /*		     -C == allow nested comments */
# /*		     -k == standard stack frame  */
# /*		     -N == enable check checking */
# /*		     -v == include debug info	 */
# /*		     -y == include line numbers  */
MODEL  = l
#CFLAGS1 = -c -m$(MODEL) -f- -C -G -O -Z -k- -d -w+ -H=XENIA.SYM -D__PROTO__
#CFLAGS2 = -c -m$(MODEL) -f- -C -G -O -Z -k- -d -w+ -H=XENIA.SYM -D__PROTO__
CFLAGS1 = -c -m$(MODEL) -f- -C -G -O -Z -k- -d -w+ -H=XENIA.SYM -Y -D__PROTO__
CFLAGS2 = -c -m$(MODEL) -f- -C -G -O -Z -k- -d -w+ -H=XENIA.SYM -Yo -D__PROTO__
TFLAGS = /mx /v /z /zi /w2 /DMODL=large
LFLAGS = /x/c/d
#debug link LFLAGS = /m/l/s/c/d/v

# Object files that BC++ 3.1 is responsible for generating:
ZMODEM = zmisc.obj zrecv.obj zsend.obj zvars.obj
XENIA1 = xenia.obj misc.obj twindow.obj tmenu.obj \
	 syspc.obj aglcom.obj
XENIA2 = sealink.obj xfer.obj modem.obj getnode.obj \
	 tmailer.obj msession.obj mailer.obj outblist.obj period.obj \
	 sched.obj bbs.obj wzsend.obj tconf.obj request.obj \
	 cdog.obj get.obj md5.obj fmisc.obj emsi.obj hydra.obj faxrecv.obj \
	 dos_file.obj script.obj exec.obj \
	 $(ZMODEM)

# Object files that TASM 3.1 is responsible for generating:
TOBJS  = checkpat.obj spawn.obj crc.obj

# Just plain objects, no sources to compile/assemble
OOBJS  = x00c$(MODEL).obj

# Dependency list for regular version, and LINK command lines
all:	 xenia.exe

xenia.exe:  $(XENIA1) $(XENIA2) $(TOBJS) $(OOBJS) makefile
	 tlink $(LFLAGS) c0$(MODEL) $(XENIA1) /o $(XENIA2) /o- $(TOBJS) $(OOBJS),$*,NUL,\
	 OVERLAY C$(MODEL) AGLWIN_$(MODEL);

# Dependencies for .C files and compiler line to generate 'em.
$(XENIA1): $*.c xenia.h
	  bcc $(CFLAGS1) $*.c

$(XENIA2): $*.c xenia.h
	  bcc $(CFLAGS2) $*.c

# Modules with special includes here
request.obj:	  request.h
syspc.obj:	  aglcom.h
aglcom.obj:	  aglcom.h
$(ZMODEM)  :	  zmodem.h

# Dependencies for .ASM files and compiler line to generate 'em.
$(TOBJS): $*.asm
	  tasm $(TFLAGS) $*;

###############################################################################
